### ISSUE TITLE
Enhance default logging

### ISSUE THREAD

**Issue by mnhauke** [troglobit/uftpd#28]
In ad-hoc ftp/tftp scenarios it would be nice to also have logging for:
* requested files, even if those could not be found on the server
* requested files in case those aren't accessable (insufficient permissions,...)

in non-debug log levels (notice/info).

**Comment by troglobit** [comment]
Good idea!  I've intentionally reduced the verbosity until a request like yours. 

These events are possibly to be classified as `LOG_NOTICE`, rather than `LOG_INFO` which has lower priority.  The `notice` log level is also the default of `uftpd`, so that would also make sense.  A user who don't want these messages could either filter them out in `/etc/syslogd.conf` or adjust the log-level `uftpd` is started with to `error`.  What do you think, would you like to submit a patch/pull-request?

**Comment by mnhauke** [comment]
https://github.com/troglobit/uftpd/pull/29
